version: "3.1"
services:
  jenkins_server:
    container_name: jenkins_server
    build:
      context: jenkins
      dockerfile: Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins:/var/jenkins_home